custom:
  db:
    url: 'postgresql://localhost:5432/r2dbc'
    username: postgres
    password: postgres

spring:
  r2dbc:
    url: r2dbc:${custom.db.url}
    username: ${custom.db.username}
    password: ${custom.db.password}
    pool:
      validation-query: select 1
    properties:
      lock_timeout: 40000
      statement_timeout: 40000
      idle_in_transaction_session_timeout: 40000
      connectTimeout: PT55S
  flyway:
#    url: jdbc:postgresql://localhost:5432;database=cps
    url: jdbc:${custom.db.url}
    user: ${custom.db.username}
    password: ${custom.db.password}
    schemas: public
  redis:
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  profiles:
    active: dev
server:
  port: 9000

